/**
 * productsData.js
 * Exports only CATEGORIES — the static app-level category definitions.
 * All product data is now fetched live from DummyJSON via:
 *   src/api/productsAPI.js  +  src/hooks/useProducts.js
 */

export const CATEGORIES = [
  { id: "electronics",  label: "Electronics",   emoji: "💻", color: "#232f3e" },
  { id: "fashion",      label: "Fashion",        emoji: "👕", color: "#c45500" },
  { id: "beauty",       label: "Beauty",         emoji: "💄", color: "#e91e8c" },
  { id: "home-kitchen", label: "Home & Kitchen", emoji: "🏠", color: "#0066c0" },
  { id: "jewelry",      label: "Jewelry",        emoji: "💍", color: "#7c3f8b" },
  { id: "accessories",  label: "Accessories",    emoji: "🎒", color: "#b12704" },
  { id: "sports",       label: "Sports",         emoji: "⚽", color: "#1a7a4a" },
];

// Legacy static products removed — all product data now served by DummyJSON API.
// eslint-disable-next-line no-unused-vars
const PRODUCTS = [];

/*
    rating: 3,
    reviewCount: 1842,
    image: "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SX466_.jpg",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SX466_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/6125mFrzr6L._AC_SX355_.jpg",
    ],
    badge: "Best Seller",
    description:
      "Experience an immersive gaming environment with Samsung's 49-inch curved gaming monitor. With a 120Hz refresh rate, 1ms response time, and HDR600 support, every frame is fluid and vivid. Super Ultra Wide 32:9 aspect ratio replaces the need for a dual-monitor setup.",
    features: [
      "49-inch curved screen with 1800R curvature",
      "5120 x 1440 QHD resolution",
      "120Hz refresh rate & 1ms response time",
      "AMD FreeSync 2 Pro — no screen tearing",
      "2× HDMI 2.0, 1× DisplayPort 1.4",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "90829332",
    category: "electronics",
    title: "Samsung 49-inch Curved LED Monitor - Super Ultra Wide Dual WQHD 5120x1440",
    price: 1094.98,
    rating: 4,
    reviewCount: 654,
    image: "https://images-na.ssl-images-amazon.com/images/I/6125mFrzr6L._AC_SX355_.jpg",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/6125mFrzr6L._AC_SX355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71Swqqe7XAL._AC_SX466_.jpg",
    ],
    badge: "Deal of the Day",
    description:
      "The ultimate productivity and gaming display. Dual WQHD resolution in a single monitor with an ultra-responsive 1ms panel. Designed to eliminate cable clutter and enhance your desk setup.",
    features: [
      "Dual WQHD (5120 × 1440) resolution",
      "Quantum HDR 1000",
      "USB-C with 90W power delivery",
      "Picture-in-Picture / Picture-by-Picture mode",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "23445930",
    category: "electronics",
    title: "Amazon Echo (3rd Generation) | Smart Speaker with Alexa, Charcoal Fabric",
    price: 98.99,
    rating: 5,
    reviewCount: 24501,
    image: "https://media.very.co.uk/i/very/P6LTG_SQ1_0000000071_CHARCOAL_SLf?$300x400_retinamobilex2$",
    images: [
      "https://media.very.co.uk/i/very/P6LTG_SQ1_0000000071_CHARCOAL_SLf?$300x400_retinamobilex2$",
    ],
    badge: "Amazon's Choice",
    description:
      "Meet Echo — the smart speaker with Alexa. Ask Alexa to play music, answer questions, read the news, check the weather, set alarms, control compatible smart home devices, and more.",
    features: [
      "Improved speaker with Dolby processing",
      "Voice control your music",
      "Smart home hub built-in (Zigbee)",
      "Privacy controls — microphone off button",
      "Works with Amazon Music, Spotify, Apple Music",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "3254354345",
    category: "electronics",
    title: "New Apple iPad Pro 12.9-inch, Wi-Fi, 128GB – Silver (4th Generation)",
    price: 598.99,
    rating: 4,
    reviewCount: 9823,
    image: "https://images-na.ssl-images-amazon.com/images/I/816ctt5WV5L._AC_SX385_.jpg",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/816ctt5WV5L._AC_SX385_.jpg",
    ],
    badge: "New",
    description:
      "iPad Pro is the ultimate iPad experience. With the powerful A12X Bionic chip, the Liquid Retina display, Face ID, and the all-new Apple Pencil (2nd generation), iPad Pro redefines what it means to be pro.",
    features: [
      "12.9-inch Liquid Retina display with ProMotion",
      "A12X Bionic chip with Neural Engine",
      "Face ID for secure authentication",
      "USB-C connector — supports external storage",
      "All-day battery life",
    ],
    inStock: true,
    prime: true,
  },

  // ── Fashion ─────────────────────────────────────────────────
  {
    id: "3",
    category: "fashion",
    title: "Mens Cotton Jacket – Slim Fit, Lightweight",
    price: 55.99,
    rating: 4,
    reviewCount: 3120,
    image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    images: ["https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg"],
    badge: "Best Seller",
    description:
      "A slim-fit cotton jacket perfect for layering in any season. Lightweight yet warm, with a modern silhouette that pairs well with jeans, chinos, or smart trousers.",
    features: [
      "100% premium cotton outer shell",
      "Slim fit — true to size",
      "2 front zip pockets + 1 inner pocket",
      "Machine washable",
      "Available in 6 colours",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "4",
    category: "fashion",
    title: "Mens Casual Slim Fit T-Shirt",
    price: 15.99,
    rating: 3,
    reviewCount: 7821,
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    images: ["https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg"],
    badge: null,
    description:
      "A casual, easy-fitting men's t-shirt made from soft breathable cotton. Great for everyday use, lounging at home, or casual outings.",
    features: [
      "95% cotton, 5% spandex blend",
      "Slim fit cut",
      "Crew neck",
      "Machine wash cold",
      "Pack of 1",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "5",
    category: "fashion",
    title: "Mens Casual Premium Slim Fit T-Shirts (Pack of 5)",
    price: 22.3,
    rating: 5,
    reviewCount: 11204,
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    images: ["https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg"],
    badge: "Amazon's Choice",
    description:
      "Get more for less with this value pack of 5 premium slim-fit t-shirts. Each shirt is made from soft cotton blend fabric for all-day comfort.",
    features: [
      "Pack of 5 assorted colours",
      "Premium cotton blend",
      "Slim fit, crew neck",
      "Machine washable",
      "Sizes S–3XL",
    ],
    inStock: true,
    prime: true,
  },

  // ── Books ───────────────────────────────────────────────────
  {
    id: "12321341",
    category: "books",
    title: "The Lean Startup: How Constant Innovation Creates Radically Successful Businesses",
    price: 11.96,
    rating: 5,
    reviewCount: 32198,
    image: "https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._SX325_BO1,204,203,200_.jpg",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._SX325_BO1,204,203,200_.jpg",
      "https://m.media-amazon.com/images/I/61PwVKrXe3L._AC_SX679_.jpg",
    ],
    description:
      "Eric Ries presents a scientific approach to creating and managing successful startups in an age when companies need to innovate more than ever. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.",
    features: [
      "Published by Currency (2011)",
      "336 pages",
      "ISBN-13: 978-0307887894",
      "Available in Hardcover, Paperback, Kindle",
      "#1 Bestseller in Entrepreneurship",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "44556677",
    category: "books",
    title: "The Lean Startup (Illustrated Edition) Paperback",
    price: 11.96,
    rating: 5,
    reviewCount: 5412,
    image: "https://m.media-amazon.com/images/I/61PwVKrXe3L._AC_SX679_.jpg",
    images: ["https://m.media-amazon.com/images/I/61PwVKrXe3L._AC_SX679_.jpg"],
    badge: null,
    description:
      "Fully illustrated companion edition of the bestselling Lean Startup. Visual guides and infographics make the core concepts even more accessible for founders and product managers.",
    features: [
      "Full-colour illustrated edition",
      "256 pages",
      "Perfect for visual learners",
      "Great gift for entrepreneurs",
    ],
    inStock: true,
    prime: true,
  },

  // ── Home & Kitchen ──────────────────────────────────────────
  {
    id: "49538094",
    category: "home-kitchen",
    title: "Kenwood kMix Stand Mixer for Baking – 5 Litre Glass Bowl",
    price: 239.0,
    rating: 4,
    reviewCount: 1987,
    image: "https://images-na.ssl-images-amazon.com/images/I/81O%2BGNdkzKL._AC_SX450_.jpg",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81O%2BGNdkzKL._AC_SX450_.jpg",
    ],
    badge: "Best Seller",
    description:
      "The Kenwood kMix stand mixer is a design icon in the kitchen. With a 5L glass bowl, planetary mixing action, and interchangeable attachments, it handles everything from light sponges to heavy dough effortlessly.",
    features: [
      "5 litre transparent glass bowl",
      "1000W motor with 6 speed settings",
      "Includes K-beater, dough hook, and balloon whisk",
      "Splash guard included",
      "Attachment hub for optional accessories",
    ],
    inStock: true,
    prime: true,
  },

  // ── Jewelry ─────────────────────────────────────────────────
  {
    id: "2",
    category: "jewelry",
    title: "Solid Gold Petite Micropave Diamond Ring",
    price: 168.0,
    rating: 5,
    reviewCount: 892,
    image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    images: ["https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg"],
    badge: "Amazon's Choice",
    description:
      "A stunning petite micropave diamond-set gold ring, perfect for everyday wear or as a subtle accent ring. Handcrafted in solid 14K gold, this ring is elegant yet understated.",
    features: [
      "Solid 14K yellow / white / rose gold",
      "0.05 ct total diamond weight",
      "Conflict-free diamonds, G-H color, SI clarity",
      "Available in sizes 5–8",
      "Gift-ready jewellery box included",
    ],
    inStock: true,
    prime: false,
  },

  // ── Accessories ─────────────────────────────────────────────
  {
    id: "1",
    category: "accessories",
    title: "Fjallraven – Foldsack No. 1 Backpack, Fits 15 Laptops",
    price: 109.0,
    rating: 4,
    reviewCount: 4521,
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    images: ["https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"],
    badge: "Best Seller",
    description:
      "The Fjallraven Foldsack No. 1 is a practical and stylish backpack that fits a 15\" laptop. Made from durable G-1000 HeavyDuty fabric, it's resistant to water, dirt, and wear — perfect for commuters and travellers alike.",
    features: [
      "Capacity: 16L",
      "Laptop compartment up to 15 inches",
      "G-1000 HeavyDuty Eco fabric",
      "Water and dirt resistant",
      "Dimensions: 44 × 30 × 13 cm",
    ],
    inStock: true,
    prime: true,
  },

  // ── Electronics (additional) ────────────────────────────────
  {
    id: "el001",
    category: "electronics",
    title: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin Monitor",
    price: 279.99,
    rating: 4,
    reviewCount: 2389,
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    images: [
      "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
      "https://fakestoreapi.com/img/81D8pNSPS3L._AC_SX679_.jpg",
    ],
    badge: "Amazon's Choice",
    description:
      "Acer SB220Q IPS ultra-thin full HD monitor sports a 75Hz refresh rate and AMD FreeSync technology for smooth rendering. Its ZeroFrame design provides minimal borders for a stunning visual experience.",
    features: [
      "21.5\" Full HD 1920×1080 IPS panel",
      "75Hz refresh rate with AMD FreeSync",
      "Ultra-thin ZeroFrame design",
      "HDMI & VGA ports",
      "Tilt-adjustable stand",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "el002",
    category: "electronics",
    title: "WD 1TB Elements Portable External Hard Drive – USB 3.0",
    price: 64.0,
    rating: 3,
    reviewCount: 7823,
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    images: ["https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg"],
    badge: null,
    description:
      "WD Elements portable drives come in a tough, reliable enclosure and use USB 3.0 for fast data transfer. Compact enough to fit in your pocket, powerful enough to hold your whole digital life.",
    features: [
      "1TB storage capacity",
      "USB 3.0 (USB 2.0 compatible)",
      "Sleek, compact design",
      "Works with PC & Mac",
      "WD SmartWare Pro backup software included",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "el003",
    category: "electronics",
    title: "SanDisk SSD PLUS 1TB Internal SSD – SATA III 6Gb/s",
    price: 109.0,
    rating: 5,
    reviewCount: 11032,
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    images: ["https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg"],
    badge: "Best Seller",
    description:
      "Upgrade from an HDD to a high-performance SanDisk SSD and see a dramatic improvement in boot times, application loading and file transfers. The SanDisk SSD PLUS shoots up to 535MB/s read and 445MB/s write.",
    features: [
      "1TB capacity",
      "Read up to 535MB/s, write up to 445MB/s",
      "SATA III 6Gb/s interface",
      "2.5\" / 7mm form factor",
      "3-year limited warranty",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "el004",
    category: "electronics",
    title: "Silicon Power 256GB SSD 3D NAND with R/W up to 560/530MB/s",
    price: 58.99,
    rating: 5,
    reviewCount: 8921,
    image: "https://fakestoreapi.com/img/71kEqp3aZaL._AC_SX679_.jpg",
    images: ["https://fakestoreapi.com/img/71kEqp3aZaL._AC_SX679_.jpg"],
    badge: "Amazon's Choice",
    description:
      "Silicon Power A55 SSD uses 3D NAND flash memory to deliver superior read/write speeds and extraordinary endurance. SLC caching technology enables blazing-fast performance for everyday computing tasks.",
    features: [
      "256GB 3D NAND flash",
      "Read up to 560MB/s, write up to 530MB/s",
      "SLC caching for burst speed",
      "SATA III 6Gb/s, 2.5\" 7mm",
      "5-year warranty",
    ],
    inStock: true,
    prime: true,
  },

  // ── Fashion – Women (additional) ────────────────────────────
  {
    id: "fa001",
    category: "fashion",
    title: "BIYLACLESEN Women's 3-in-1 Skiing Jacket Windproof Waterproof",
    price: 56.99,
    rating: 3,
    reviewCount: 2341,
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    images: ["https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg"],
    badge: null,
    description:
      "Stay warm and dry with this versatile 3-in-1 skiing jacket. The outer shell is windproof and waterproof, while the inner fleece can be worn separately for layering versatility.",
    features: [
      "3-in-1 design — outer shell + inner fleece",
      "Windproof & waterproof outer",
      "Fleece inner layer removable",
      "Adjustable hood and cuffs",
      "Available in multiple colours",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "fa002",
    category: "fashion",
    title: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: 29.95,
    rating: 2,
    reviewCount: 1872,
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    images: ["https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg"],
    badge: null,
    description:
      "Edgy faux-leather moto jacket with a removable hood for styling versatility. Great for autumn/spring layering, pair it over a hoodie or maxi dress for a bold look.",
    features: [
      "Faux leather exterior",
      "Removable hood",
      "Asymmetric front zipper",
      "4 front pockets",
      "Biker-inspired hardware detailing",
    ],
    inStock: true,
    prime: false,
  },
  {
    id: "fa003",
    category: "fashion",
    title: "MBJ Women's Solid Short Sleeve Boat Neck V Neck Blouse Top",
    price: 9.85,
    rating: 3,
    reviewCount: 5123,
    image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    images: ["https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg"],
    badge: "Best Value",
    description:
      "A casual yet chic women's blouse made from a soft, lightweight fabric. The relaxed fit and boat neckline give it an effortless, everyday style that pairs well with jeans or trousers.",
    features: [
      "95% Rayon, 5% Spandex",
      "Short sleeve, relaxed fit",
      "Boat neck / V-neck option",
      "Hand wash or gentle machine wash",
      "Sizes S–3XL",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "fa004",
    category: "fashion",
    title: "Opna Women's Short Sleeve Moisture Tunic – Curved Hem",
    price: 7.95,
    rating: 4,
    reviewCount: 3412,
    image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    images: ["https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg"],
    badge: "Amazon's Choice",
    description:
      "Lightweight moisture-wicking tunic perfect for athletic activities, yoga, or casual wear. The curved hem provides extra coverage and a flattering silhouette.",
    features: [
      "Moisture-wicking fabric",
      "UPF 50+ sun protection",
      "Curved hem for flattering fit",
      "Side vents for breathability",
      "Machine washable",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "fa005",
    category: "fashion",
    title: "DANVOUY Womens T Shirt Casual Cotton Short",
    price: 12.99,
    rating: 3,
    reviewCount: 4218,
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    images: ["https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg"],
    badge: null,
    description:
      "Casual everyday cotton t-shirt for women. Soft, breathable, and available in a wide range of colours to mix and match with any outfit.",
    features: [
      "100% combed cotton",
      "Relaxed casual fit",
      "Round neck, short sleeves",
      "Machine washable",
      "Available in 12 colours",
    ],
    inStock: true,
    prime: true,
  },

  // ── Jewelry (additional) ─────────────────────────────────────
  {
    id: "jw001",
    category: "jewelry",
    title: "John Hardy Women's Legends Naga Gold & Silver Dragon Bracelet",
    price: 695.0,
    rating: 4,
    reviewCount: 412,
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    images: ["https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg"],
    badge: "Luxury Pick",
    description:
      "From the John Hardy Legends Naga collection, this stunning bracelet features hand-crafted sterling silver and 18K gold dragon detailing. A bold statement piece inspired by Balinese mythology.",
    features: [
      "Sterling silver & 18K gold",
      "Hand-crafted in Bali",
      "Dragon-head clasp design",
      "Adjustable chain length",
      "Comes in John Hardy gift box",
    ],
    inStock: true,
    prime: false,
  },
  {
    id: "jw002",
    category: "jewelry",
    title: "White Gold Plated Princess Cut CZ Stud Earrings",
    price: 9.99,
    rating: 3,
    reviewCount: 8231,
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    images: ["https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg"],
    badge: "Best Value",
    description:
      "Classic princess-cut cubic zirconia stud earrings plated in white gold. Sparkling and elegant, these earrings are perfect for everyday wear or special occasions.",
    features: [
      "White gold plated sterling silver",
      "Princess-cut cubic zirconia",
      "Secure push-back closure",
      "Hypoallergenic",
      "Gift pouch included",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "jw003",
    category: "jewelry",
    title: "Pierced Owl Rose Gold Plated Stainless Steel Double Flared Plug",
    price: 10.99,
    rating: 1,
    reviewCount: 591,
    image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    images: ["https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg"],
    badge: null,
    description:
      "Rose gold plated stainless steel double-flared ear gauges. Lightweight, durable, and non-irritating — perfect for stretched earlobes.",
    features: [
      "316L surgical stainless steel",
      "Rose gold PVD coating",
      "Double-flared design",
      "Available in sizes 6G–00G",
      "Sold as a pair",
    ],
    inStock: true,
    prime: true,
  },

  // ── Books (additional) ───────────────────────────────────────
  {
    id: "bk001",
    category: "books",
    title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    price: 14.99,
    rating: 5,
    reviewCount: 98231,
    image: "https://covers.openlibrary.org/b/isbn/0735211299-L.jpg",
    images: ["https://covers.openlibrary.org/b/isbn/0735211299-L.jpg"],
    badge: "Best Seller",
    description:
      "James Clear's #1 New York Times bestseller reveals how tiny changes in behaviour can lead to remarkable results. A practical guide to building good habits and breaking bad ones using proven science.",
    features: [
      "Published by Avery (2018)",
      "320 pages",
      "ISBN-13: 978-0735211292",
      "#1 NYT Bestseller",
      "Available in Hardcover, Paperback, Kindle, Audio",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "bk002",
    category: "books",
    title: "Deep Work: Rules for Focused Success in a Distracted World",
    price: 13.49,
    rating: 5,
    reviewCount: 45102,
    image: "https://covers.openlibrary.org/b/isbn/1455586692-L.jpg",
    images: ["https://covers.openlibrary.org/b/isbn/1455586692-L.jpg"],
    badge: "Editor's Pick",
    description:
      "Cal Newport argues that the ability to perform deep, focused work is becoming increasingly rare and increasingly valuable. This book teaches you how to cultivate a deep-work ethic in a world full of distraction.",
    features: [
      "Published by Grand Central Publishing (2016)",
      "296 pages",
      "ISBN-13: 978-1455586691",
      "Wall Street Journal bestseller",
      "Available in Hardcover, Paperback, Kindle",
    ],
    inStock: true,
    prime: true,
  },

  // ── Sports (new category) ────────────────────────────────────
  {
    id: "sp001",
    category: "sports",
    title: "Fitbit Charge 5 Advanced Fitness & Health Tracker",
    price: 129.95,
    rating: 4,
    reviewCount: 18203,
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    images: ["https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg"],
    badge: "Best Seller",
    description:
      "Fitbit Charge 5 helps you understand your body and prioritise your health with an EDA Scan app, ECG app, stress management score and built-in GPS. Comes with 6 months of Fitbit Premium.",
    features: [
      "Built-in GPS for real-time pace & distance",
      "ECG app for heart rhythm assessment",
      "Daily Readiness Score (with Fitbit Premium)",
      "Sleep tracking & SpO2 monitoring",
      "Up to 7-day battery life",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "sp002",
    category: "sports",
    title: "Yoga Mat – Non Slip Extra Thick 6mm, 183×61cm with Carry Strap",
    price: 24.99,
    rating: 4,
    reviewCount: 7821,
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=400&q=80"],
    badge: "Amazon's Choice",
    description:
      "Premium non-slip yoga mat with double-sided grip for optimal stability. 6mm extra thickness provides superior cushioning for joints during yoga, pilates, or home workouts.",
    features: [
      "6mm thick NBR foam",
      "Non-slip surface both sides",
      "183 × 61cm standard size",
      "Includes carry strap",
      "Easy to clean — wipe with damp cloth",
    ],
    inStock: true,
    prime: true,
  },

  // ── Home & Kitchen (additional) ──────────────────────────────
  {
    id: "hk002",
    category: "home-kitchen",
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker, 6 Quart",
    price: 89.99,
    rating: 5,
    reviewCount: 43219,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80"],
    badge: "Best Seller",
    description:
      "The Instant Pot Duo is America's #1 best-selling multi-cooker. It replaces 7 kitchen appliances — pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.",
    features: [
      "7-in-1 functionality",
      "6-quart capacity — serves 4–6",
      "14 one-touch smart programmes",
      "UL/ULC certified safety features",
      "Dishwasher-safe lid and inner pot",
    ],
    inStock: true,
    prime: true,
  },
  {
    id: "hk003",
    category: "home-kitchen",
    title: "Nespresso Vertuo Next Coffee and Espresso Machine by De'Longhi",
    price: 149.99,
    rating: 4,
    reviewCount: 11820,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80"],
    badge: "Amazon's Choice",
    description:
      "Nespresso VertuoNext uses Centrifusion™ technology to brew five cup sizes — Espresso, Double Espresso, Gran Lungo, Coffee, and Alto — all with a single touch. With WiFi-enabled smart features for the ultimate coffee experience.",
    features: [
      "Brews 5 cup sizes with one touch",
      "Centrifusion™ extraction technology",
      "WiFi-connected for smart updates",
      "Rapid heat in 30 seconds",
      "Includes 12 complimentary capsules",
    ],
    inStock: true,
    prime: true,
  },
];
*/

// Stub helpers kept for any legacy import that hasn't been migrated yet.
export const getProductById = () => null;
export const getProductsByCategory = () => [];